### ISSUE TITLE
Erreur à l'alignement

### ISSUE THREAD

**Issue by clrh** [Transition-bibliographique/bibliostratus#61]
Bonjour,

Avec le fichier ci-dessous, j'obtiens une erreur à l'alignement des données
```
31. 1116 : ark:/12148/cb42731915b
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/claire/dev/bibliostratus/bibliostratus/bib2id.py", line 3151, in <lambda>
    id_traitement.get(),
  File "/home/claire/dev/bibliostratus/bibliostratus/bib2id.py", line 2640, in launch
    file2row(form_bib2ark, zone_controles, entry_filename, liste_reports, parametres)
  File "/home/claire/dev/bibliostratus/bibliostratus/bib2id.py", line 2593, in file2row
    item2id(row, n, form_bib2ark, parametres, liste_reports)
  File "/home/claire/dev/bibliostratus/bibliostratus/bib2id.py", line 2515, in item2id
    alignment_result = item_alignement(input_record, parametres)
  File "/home/claire/dev/bibliostratus/bibliostratus/bib2id.py", line 2485, in item_alignement
    ark = item2ppn_by_keywords(input_record, parametres)
  File "/home/claire/dev/bibliostratus/bibliostratus/bib2id.py", line 2437, in item2ppn_by_keywords
    ppn = tad2ppn(input_record, parametres)
  File "/home/claire/dev/bibliostratus/bibliostratus/bib2id.py", line 1850, in tad2ppn
    listePPN = urlsudoc2ppn(url)
  File "/home/claire/dev/bibliostratus/bibliostratus/bib2id.py", line 1894, in urlsudoc2ppn
    (test, page) = funcs.testURLurlopen(url, display=False, timeout_def=10)
  File "/home/claire/dev/bibliostratus/bibliostratus/funcs.py", line 718, in testURLurlopen
    resultat = request.urlopen(url, timeout=timeout_def)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1265, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/lib/python3.6/http/client.py", line 1127, in putrequest
    raise InvalidURL(f"URL can't contain control characters. {url!r} "
http.client.InvalidURL: URL can't contain control characters. '//DB=2.1/SET=18/TTL=1/CMD?ACT=SRCHM&MATCFILTER=Y&MATCSET=Y&NOSCAN=Y&PARSE_MNEMONICS=N&PARSE_OPWORDS=N&PARSE_OLDSETS=N&IMPLAND=Y&ACT0=SRCHA&screen_mode=Recherche&IKT0=1004&TRM0=willefrand&ACT1=*&IKT1=4&TRM1=decouverte%20de%20barcelone&ACT2=*&IKT2=1016&TRM2=&ACT3=*&IKT3=1016&TRM3=&SRT=YOP&ADI_TAA=&ADI_LND=&ADI_JVU=2011& ADI_MAT = B' (found at least ' ')
```

[export-1053.txt](https://github.com/Transition-bibliographique/bibliostratus/files/3793244/export-1053.txt)

Version master sur :
```
commit f970254adb4123d3b52b7f73e4a623659f9c6ec7 (origin/master, origin/HEAD)
Author: Lullly <lully1804@yahoo.fr>
Date:   Fri Oct 4 09:07:45 2019 +0200

    Option csv/tsv

```

Merci.

**Comment by Lully** [comment]
@clrh Désolé, cela fait très longtemps que je n'étais pas passé par ici. C'est corrigé en master à partir de la version 1.28 (16/01/2020)

**Comment by clrh** [comment]
Super, merci beaucoup :)
