### ISSUE TITLE
Exception in Tkinter callback

### ISSUE THREAD

**Issue by msaby** [Transition-bibliographique/bibliostratus#64]
Bonjour
J'ai eu ce bug en exécutant bibliostratus à partir de la source, sous windows (version master téléchargée le 26.3.2020) lors de la recherche dans le Sudoc à partir d'un fichier tabulé. Tout s'est bien passé jusqu'à la ligne 731.
J'ai essayé de relancer l'opération en redécoupant mon fichier pour commencer à la ligne 731, et l'erreur ne s'est pas reproduite. Donc l'erreur ne doit pas venir d'une anomalie dans cette ligne ni dans la ligne suivante.

c'est un gros fichier (6000 lignes), donc c'est assez frustrant...

731. VAR3929360 :
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\MATHIEU\Miniconda3\lib\http\client.py", line 544, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "C:\Users\MATHIEU\Miniconda3\lib\http\client.py", line 511, in _read_next_chunk_size
    return int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MATHIEU\Miniconda3\lib\http\client.py", line 576, in _readinto_chunked
    chunk_left = self._get_chunk_left()
  File "C:\Users\MATHIEU\Miniconda3\lib\http\client.py", line 546, in _get_chunk_left
    raise IncompleteRead(b'')
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MATHIEU\Miniconda3\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\PROJETS\bibliostratus_ms\bibliostratus\bib2id.py", line 2736, in <lambda>
    form_bib2ark,
  File "C:\PROJETS\bibliostratus_ms\bibliostratus\bib2id.py", line 2405, in launch
    file2row(form_bib2ark, entry_filename, liste_reports, parametres)
  File "C:\PROJETS\bibliostratus_ms\bibliostratus\bib2id.py", line 2352, in file2row
    item2id(row, n, form_bib2ark, parametres, liste_reports)
  File "C:\PROJETS\bibliostratus_ms\bibliostratus\bib2id.py", line 2281, in item2id
    alignment_result = item_alignement(input_record, parametres)
  File "C:\PROJETS\bibliostratus_ms\bibliostratus\bib2id.py", line 2253, in item_alignement
    ark = item2ppn_by_id(input_record, parametres)
  File "C:\PROJETS\bibliostratus_ms\bibliostratus\bib2id.py", line 2107, in item2ppn_by_id
    ppn = isbn2sudoc(input_record, parametres)
  File "C:\PROJETS\bibliostratus_ms\bibliostratus\bib2id.py", line 797, in isbn2sudoc
    isbnTrouve = funcs.testURLretrieve(url)
  File "C:\PROJETS\bibliostratus_ms\bibliostratus\funcs.py", line 702, in testURLretrieve
    request.urlretrieve(url)
  File "C:\Users\MATHIEU\Miniconda3\lib\urllib\request.py", line 276, in urlretrieve
    block = fp.read(bs)
  File "C:\Users\MATHIEU\Miniconda3\lib\http\client.py", line 447, in read
    n = self.readinto(b)
  File "C:\Users\MATHIEU\Miniconda3\lib\http\client.py", line 481, in readinto
    return self._readinto_chunked(b)
  File "C:\Users\MATHIEU\Miniconda3\lib\http\client.py", line 592, in _readinto_chunked
    raise IncompleteRead(bytes(b[0:total_bytes]))
http.client.IncompleteRead: IncompleteRead(0 bytes read)
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\MATHIEU\Miniconda3\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\PROJETS\bibliostratus_ms\bibliostratus\main.py", line 677, in <lambda>
    master, access_to_network, [0, False]
  File "C:\PROJETS\bibliostratus_ms\bibliostratus\bib2id.py", line 2785, in form_bib2id
    tk.mainloop()
  File "C:\Users\MATHIEU\Miniconda3\lib\tkinter\__init__.py", line 560, in mainloop
    _default_root.tk.mainloop(n)
KeyboardInterrupt
Traceback (most recent call last):
  File "main.py", line 808, in <module>
    forms.default_launch()
  File "C:\PROJETS\bibliostratus_ms\bibliostratus\forms.py", line 281, in default_launch
    main.formulaire_main(access_to_network, last_version)
  File "C:\PROJETS\bibliostratus_ms\bibliostratus\main.py", line 800, in formulaire_main
    tk.mainloop()
  File "C:\Users\MATHIEU\Miniconda3\lib\tkinter\__init__.py", line 560, in mainloop
    _default_root.tk.mainloop(n)
KeyboardInterrupt
Terminer le programme de commandes (O/N) ? O

**Comment by msaby** [comment]
ça ressemble à ça https://stackoverflow.com/questions/48241191/writing-writing-a-large-text-file-in-python3

**Comment by Lully** [comment]
Salut @msaby Tu donnerais un copier coller des lignes 730 à 740 ? Il doit y avoir un problème de non-conformité dans les données,  non prévu par le programme

**Comment by msaby** [comment]
VAR3929269					willi kopf zeichnungen exposition wien galerie grita insam 1988	grita insam galerie	1988		galerie grita insam
VAR3929343					maurice lemaître exposition livorno galleria peccolo novembre 2003	mirella galleria peccolo bandini	2003		galleria peccolo
VAR3929347					florence valay sculptures 1984 1987 exposition paris galerie regards 1987 rome villa medicis académie france rome 1987	renaud rome camus academie france	1987		galerie regards académie france rome
VAR3929360					 levine media ptojects  public advertisements exposition luzern mai galerie februar april 1988	yau greenwald john galerie mai ted	1988		mai galerie
VAR3929428			3-906537-09-9		reto leibundgut exposition thun kunstmuseum april mai 2002	schuppli kunstmuseum madeleine suzanne friedli	2002		kunstmuseum
VAR3929679					manel lledos exposition barcelona galeria joan prats abril maig 1998	wei joan galeria lilly prats	1998		galeria joan prats
VAR3929709					francesca llopis embolic magnific exposition girona espais centre art contemporani del octubre desembre 1997	teresa blanch espais centre art contemporani	1997		espais centre art contemporani
VAR3929476			3-928761-27-7		thomas lehnerer figurenkreis exposition bremen neues museum weserburg vom bis 1996	peter friese neues museum weserburg	1996		neues museum weserburg
VAR3929572					gereon lepper skulpturen exposition kassel museum fridericianum 1988	veit loers fridericianum museum	1988		museum fridericianum
VAR3929736					julia lohmann corazon ausstellung düsseldrof galerie schmela april mai 1991	ulrike schmela galerie	1991		galerie ulrike schmela
VAR3929775			90-70149-32-X		bert loerakker exposition eindhoven stedelijk van abbemuseum t/m 1992	van frank abbemuseum lubbers	1992		van abbemuseum

**Comment by msaby** [comment]
`
VAR3929269					willi kopf zeichnungen exposition wien galerie grita insam 1988	grita insam galerie	1988		galerie grita insam
VAR3929343					maurice lemaître exposition livorno galleria peccolo novembre 2003	mirella galleria peccolo bandini	2003		galleria peccolo
VAR3929347					florence valay sculptures 1984 1987 exposition paris galerie regards 1987 rome villa medicis académie france rome 1987	renaud rome camus academie france	1987		galerie regards académie france rome
VAR3929360					 levine media ptojects  public advertisements exposition luzern mai galerie februar april 1988	yau greenwald john galerie mai ted	1988		mai galerie
VAR3929428			3-906537-09-9		reto leibundgut exposition thun kunstmuseum april mai 2002	schuppli kunstmuseum madeleine suzanne friedli	2002		kunstmuseum
VAR3929679					manel lledos exposition barcelona galeria joan prats abril maig 1998	wei joan galeria lilly prats	1998		galeria joan prats
VAR3929709					francesca llopis embolic magnific exposition girona espais centre art contemporani del octubre desembre 1997	teresa blanch espais centre art contemporani	1997		espais centre art contemporani
VAR3929476			3-928761-27-7		thomas lehnerer figurenkreis exposition bremen neues museum weserburg vom bis 1996	peter friese neues museum weserburg	1996		neues museum weserburg
VAR3929572					gereon lepper skulpturen exposition kassel museum fridericianum 1988	veit loers fridericianum museum	1988		museum fridericianum
VAR3929736					julia lohmann corazon ausstellung düsseldrof galerie schmela april mai 1991	ulrike schmela galerie	1991		galerie ulrike schmela
VAR3929775			90-70149-32-X		bert loerakker exposition eindhoven stedelijk van abbemuseum t/m 1992	van frank abbemuseum lubbers	1992		van abbemuseum

`

**Comment by msaby** [comment]
voici 

[l730-740.txt](https://github.com/Transition-bibliographique/bibliostratus/files/4388875/l730-740.txt)

**Comment by msaby** [comment]
voici

il y a un / dans une ligne. ça serait ça? 

[l730-740.txt](https://github.com/Transition-bibliographique/bibliostratus/files/4388902/l730-740.txt)
