### ISSUE TITLE
Message Erreur Module Blanc

### ISSUE THREAD

**Issue by Rbsma** [Transition-bibliographique/bibliostratus#69]
Bonjour, 

Tout d'abord un grand merci pour ce bel outil que vous avez créé ! Je pense qu'il va m'être très utile une fois que j'aurais réussi à le prendre en main.
Lorsque j'utilise le module blanc, j'ai un message qui s'affiche parfois et qui bloque la suite de la procédure. Sauriez-vous en quoi il consiste et comment je peux préparer mes données pour ne plus l'avoir ? Je vous le mets en pièce jointe.
J'utilise le module bleu pour préparer les fichiers avant et que j'utilise la version 1.29
Je précise aussi que je ne suis formée à l'informatique et que j'arrive à faire fonctionner Bibliostratus en me basant sur vos tutoriels. Dès qu'une prochaine formation est prévue dans le région parisienne, je m'inscris ! 

Merci d'avance pour votre aide ! 
![pblm bibliostratus](https://user-images.githubusercontent.com/68069770/87054039-f38c4200-c202-11ea-9b1b-63a1d3bfe74b.jpg)

**Comment by Lully** [comment]
Merci d'avoir constaté cette erreur, qui correspond à un cas (relativement rare, du moins dans ma propre utilisation) où on cherche un ARK à partir d'un ancien numéro. Le programme cherchait à appeler une information qui ne lui a jamais été donnée.
Pouvez-vous réessayer avec la version 1.31 (en cours de développement) : https://github.com/Transition-bibliographique/bibliostratus/raw/1.31/bin/RC/bibliostratus_1.31RC_win64_py3.6.zip

**Comment by ragbx** [comment]
Bonjour,

Je rencontre le même pb. Le correctif proposé fonctionne, mais on rencontre une autre erreur juste derrière, sur la fonction "relancerNNBAuteur" : 


joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "app/miniconda3/envs/bibliostratus/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "app/miniconda3/envs/bibliostratus/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "app/miniconda3/envs/bibliostratus/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 593, in __call__
    return self.func(*args, **kwargs)
  File "app/miniconda3/envs/bibliostratus/lib/python3.8/site-packages/joblib/parallel.py", line 252, in __call__
    return [func(*args, **kwargs)
  File "app/miniconda3/envs/bibliostratus/lib/python3.8/site-packages/joblib/parallel.py", line 252, in <listcomp>
    return [func(*args, **kwargs)
  File "dev/bibliostratus_fork/bibliostratus/bib2id.py", line 2334, in item2id
    alignment_result = item_alignement(input_record, parametres)
  File "dev/bibliostratus_fork/bibliostratus/bib2id.py", line 2300, in item_alignement
    bibid = item2ark_by_id(input_record, parametres)
  File "dev/bibliostratus_fork/bibliostratus/bib2id.py", line 2069, in item2ark_by_id
    ark = frbnf2ark(input_record)
  File "dev/bibliostratus_fork/bibliostratus/bib2id.py", line 674, in frbnf2ark
    ark = oldfrbnf2ark(input_record)
  File "dev/bibliostratus_fork/bibliostratus/bib2id.py", line 651, in oldfrbnf2ark
    ark = systemid2ark(
  File "dev/bibliostratus_fork/bibliostratus/bib2id.py", line 591, in systemid2ark
    listeARK = relancerNNBAuteur(input_record, NumNot, systemid, isbn,
  File "dev/bibliostratus_fork/bibliostratus/bib2id.py", line 270, in relancerNNBAuteur
    listeArk.append(ark)
NameError: name 'ark' is not defined
"""

À la ligne 270 de bibliostratus/bib2id.py, remplacer `listeArk.append(ark)` par `listeArk.append(ark_current)` semble corriger le pb.

**Comment by Lully** [comment]
Suite à la remarque de @ragbx j'ai apporté une correction dans le code et recompilé la 1.31RC (en une 1.31.4RC) : 
https://github.com/Transition-bibliographique/bibliostratus/blob/1.31/bin/RC/bibliostratus_1.31.4RC_win64_py3.6.zip

**Comment by Rbsma** [comment]
Bonjour, 

J'ai refait un test avec la version 1.31 et je n'ai plus eu de problèmes. Merci beaucoup.
Juste une petite remarque : lorsque j'importe les ARK, les adresses commencent par tp/ au lieu du http/
Est-ce que j'ai mal paramétré quelque chose ? 

En vous remerciant d'avance.

**Comment by Lully** [comment]
@Rbsma c'est assez embêtant, mais en suivant quelle processus exactement : c'est en voulant générer avec le module rouge un fichier de notices contenant des ARK en 003 ?

**Comment by Rbsma** [comment]
Je récupère les notices avec le module rouge puis je les importe dans mon SIGB en utilisant un filtre de fusion qui ne récupère que le champs 003.
Il est tout à fait possible que ma façon de faire ne soit pas la meilleure....J'apprivoise encore Bibliostratus.

**Comment by Lully** [comment]
Ce sera possible d'avoir 3-4 lignes du fichier en entrée du module rouge, pour que je puisse reproduire le problème ?

**Comment by Rbsma** [comment]
Aucun problème. 
Par contre, je n'ai pas les fichiers ici. Je n'utilise Bibliostratus que lorsque je suis en télétravail car l'ordinateur a Windows 10.
Et je n'y aurai pas accès avant Septembre. Je note dans mon agenda de vous envoyer quelques liignes du fichier.
Encore merci de votre aide.
