### ISSUE TITLE
"Rapports de stat" est vide

### ISSUE THREAD

**Issue by clrh** [Transition-bibliographique/bibliostratus#73]
J'ai lancé bibliostratus en ligne de commande. Pour tous les fichiers traités, j'ai un rapport de stat vide.

La commande:
```
python3 /lebonpath/bibliostratus/cli.py --action bib2id --file  $file --dir $RES_DIR --prefix $filename
```

Version: commit 077d82a (master 28 décembre)

J'ai bien des résultats de notices alignées dans *resultats*.txt et *rapport_stats*.txt ne contient que les entêtes de colonnes.
```
projet-rapport_stats_bib2id.txt               15-Jan-2021 16:19                  38
projet-resultats_bib2id.txt                   15-Jan-2021 16:19               48552
```

(J'irai plus loin dans l'investigation un peu plus tard.)

**Comment by clrh** [comment]
Problème avec le paramètre "files_nb". Dans ma tentative de contournement, je trouve un problème avec le paramètre files_nb:
```
$ python3 /home/koha/bibliostratus/bibliostratus/cli.py --action bib2id --file ADER-CAR-01 --files_nb 3 --prefix test2
Traceback (most recent call last):
  File "/home/koha/bibliostratus/bibliostratus/cli.py", line 221, in <module>
    action_align()
  File "/home/koha/bibliostratus/bibliostratus/cli.py", line 126, in action_align
    args.files_nb = dic_files_number[args.files_nb.lower()]
KeyError: '3'
```
(OK avec `--files_nb 1`)

**Comment by Lully** [comment]
Logiquement, ça devrait fonctionner aussi avec `--files_nb 2`
Non ?

**Comment by clrh** [comment]
Je ne sais pas. D'après la doc c'est 1 et 3 les valeurs autorisées:
```
--files_nb : Nombre de fichiers en sortie
Valeurs autorisées : 1, 3
Défaut=1
```
Avec "2", j'ai la même réponse qu'avec "3". Est ce que "3" ne permet pas de donner les fichiers de rapports "0 ARK trouvés, 1 ARK et plusieurs" ?

J'avais l'espoir que ça me contourne mon problème initial que projet-rapport_stats_bib2id.txt soit vide.

**Comment by Lully** [comment]
Effectivement, je n'avais pas correctement configuré la liste des valeurs possibles.
Et en plus erreur dans la doc technique
J'ai corrigé les deux problèmes dans les commits du 18/01/2021 en branche 1.32 : https://github.com/Transition-bibliographique/bibliostratus/commit/b80fbaaa36a8a567b4a7bd82c562c6a5e83e59a7 et https://github.com/Transition-bibliographique/bibliostratus/commit/8b1078361eb371daeda93ef7f414e92696eaf401

**Comment by clrh** [comment]
Testé presque OK
```
python3 /home/claire/dev/bibliostratus/bibliostratus/cli.py --action bib2id --file fichier-test --files_nb 1 --prefix t.est1
t.est1-rapport_stats_bib2id.txt
t.est1-resultats_bib2id.txt
python3 /home/claire/dev/bibliostratus/bibliostratus/cli.py --action bib2id --file fichier-test --files_nb 2 --prefix t.est2

t.est2-Problemes_donnees_initiales.txt
t.est2-rapport_stats_bib2id.txt
t.est2-resultats_0_ID_trouve.txt
t.est2-resultats_1_ID_trouve.txt
t.est2-resultats_plusieurs_ID_trouves.txt

python3 /home/claire/dev/bibliostratus/bibliostratus/cli.py --action bib2id --file fichier-test --files_nb 3 --prefix t.est3
t.est3-Problemes_donnees_initiales.txt
t.est3-rapport_stats_bib2id.txt
t.est3-resultats_0_ID_trouve.txt
t.est3-resultats_1_ID_trouve.txt
t.est3-resultats_plusieurs_ID_trouves.txt
```

1.Je ne vois pas ce qui change entre --files_nb 2 et --files_nb 3
2. Je n'ai rien à part les entêtes dans `*-Problemes_donnees_initiales.txt` et `*-rapport_stats_bib2id.txt`
